---
title: "R Notebook"
output: html_notebook
---



```{r}
studio <- read.csv("C:/Users/Owner/OneDrive/Documente/data/Studio assessment 2017-2022.csv")
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(readr)
library(tidyr)
```



Count for each column
```{r}

#Q1 <- studio %>% count(NYC.Metro.Area.)
#pie(table(studio$NYC.Metro.Area.))

slices <- c(11, 20)
lbls <- c("No-", "Yes-")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="")
pie(slices,labels = lbls, col=wes_palette(n=2, "GrandBudapest1"),
   main="Number of NYC Metro Area Clients \n in GSAPP Studios (2017-2022)")
#pie(slices, labels = lbls,explode=0.1, main="Number of Clients Located in NYC Metro Area")

```
Question 2
```{r}

slices <- c(16, 13, 2)
lbls <- c("No-", "Yes-", "Unknown-")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="")
pie(slices,labels = lbls, col=c("#143151", "#5A435F","#C3C7E0"),
   main="Number of NYC Neighborhood-Specific Clients \n in Studios (2017-2022)")

#use the Wednesday color palette c("#143151", "#5A435F","#C3C7E0", "#0A0C18")
#wesanderson: col=wes_palette(n=3, name="GrandBudapest1")
#col=rainbow(length(lbls)),
```
Practice making it more beautiful with ggplot and wes anderson palette
```{r}

library(wesanderson)
paint <- wes_palette("GrandBudapest2", n=8, type="continuous")

```



Q3
```{r}
slices <- c(17, 10, 1, 3)
lbls <- c("No-", "Yes-", "Unknown-", "No and Yes-")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="")
pie(slices,labels = lbls, col=wes_palette(n=4, "GrandBudapest1"),
   main="Total Percentage of BIPOC Clients in \n Studios (2017-2022)")
```

Q4
```{r}
slices <- c(25, 4, 2)
lbls <- c("No-", "Yes-", "Unknown-")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="")
pie(slices,labels = lbls, col=wes_palette(n=3, "GrandBudapest1"),
   main="Percentage of BIPOC Clients from \n Community Based Organizations in Studios (2017-2022)")
```
Q6
```{r}
slices <- c(21, 5, 5)
lbls <- c("No-", "Yes-", "Unknown (Spring 2022)-")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="")
pie(slices,labels = lbls, col=c("#143151", "#5A435F","#C3C7E0"),
   main="Ongoing, Continued Engagement with Clients \n from Studios (2017-2022)")
```


I need to make a separate dataframe where the Columns indicating it is NYC-based is Yes
```{r}



nyc <- studio %>% filter(grepl('YES', NYC.Metro.Area.))

# %>%
#    filter(month==1) %>%
#    filter(day==1)

```







```

